#!/bin/bash

function Help() {
  cat <<EOF
Usage: amethyst-cli [option] [path_to_file]

Options:
  -h, --help                show help message
  cd                        change directory to the Amethyst dotfiles directory
  add                       add the file to the Amethyst directory
  remove                    remove the file from the Amethyst directory
EOF
}

case "$1" in
-h | --help)
  Help
  ;;
cd)
  (cd "$HOME/.local/share/amethyst/dotfiles/" && $SHELL)
  ;;
add)
  input_path="$2"
  relative_path="${input_path/#$HOME\//}"
  pushd $HOME/ &&
    rsync -aR --exclude-from="$HOME/.local/share/amethyst/dotfiles/.rsyncignore" "$relative_path" $HOME/.local/share/amethyst/dotfiles/ &&
    stow -d "$HOME/.local/share/amethyst/dotfiles/" -t $HOME/ . --adopt
  popd
  ;;
remove)
  input_path="$2"
  relative_path="${input_path/#$HOME\//}"
  rsync -a --exclude-from="$HOME/.local/share/amethyst/dotfiles/.rsyncignore" --remove-source-files "$HOME/.local/share/amethyst/dotfiles/$relative_path" "$input_path"
  ;;
*)
  echo "Unknown option: $1"
  Help
  ;;
esac
