#!/bin/bash

function Help() {
  cat <<EOF
Usage: paradox [option] [path_to_file]

Options:
  -h, --help                show help message
  cd                        change directory to the Paradox dotfiles directory
  add                       add the file to the Paradox directory
  remove                    remove the file from the Paradox directory
EOF
}

case "$1" in
-h | --help)
  Help
  ;;
cd)
  (cd "$HOME/.local/share/paradox/dotfiles/" && $SHELL)
  ;;
add)
  rsync -a --exclude-from="$HOME/.local/share/paradox/dotfiles/.rsyncignore" "$2" $HOME/.local/share/paradox/dotfiles/
  pushd "$HOME/.local/share/paradox/dotfiles/"
  stow -t $HOME/ --adopt .
  popd
  ;;
remove)
  input_path="$2"
  relative_path="${input_path/#$HOME/}"
  if [ "$relative_path" != "/" ]; then
    relative_path="${relative_path%/}"
  fi
  rsync -a --exclude-from="$HOME/.local/share/paradox/dotfiles/.rsyncignore" --remove-source-files "$HOME/.local/share/paradox/dotfiles/$relative_path" $HOME/
  ;;
*)
  echo "Unknown option: $1"
  Help
  ;;
esac
