#!/bin/bash

# This script finds the fastest mirrors

VERSION="v1.0.0"

case "$1" in
--version)
  echo "update script version $VERSION"
  exit 0
  ;;
--help | -h)
  echo "This script updates your mirrors to the fastest mirrors using rate-mirrors"
  echo "Just type 'update' to run the script"
  echo "--version   Show version"
  echo "-h, --help  Show help"
  exit 0
  ;;
-*)
  echo "Error: Unknown option '$1'" >&2
  echo "Use --help to see available options."
  echo "Just type 'update' to run the script"
  exit 1
  ;;
esac

sudo -v

# Run mirror update in background

country=$(curl -s ipinfo.io/country)

(
  # Arch mirrors
  if [ -f /etc/pacman.d/mirrorlist ]; then
    rate-mirrors --allow-root --disable-comments --protocol=https --entry-country="$country" --country-neighbors-per-country=0 arch | tee /tmp/arch_mirrorlist >/dev/null
    if [ -s /tmp/arch_mirrorlist ]; then
      sudo cp /tmp/arch_mirrorlist /etc/pacman.d/mirrorlist
   fi
  fi

  # Chaotic-AUR
  if [ -f /etc/pacman.d/chaotic-mirrorlist ]; then
    rate-mirrors --allow-root --disable-comments --protocol=https --entry-country="$country" --country-neighbors-per-country=0 chaotic-aur | tee /tmp/chaotic_mirrorlist >/dev/null
    if [ -s /tmp/chaotic_mirrorlist ]; then
      sudo cp /tmp/chaotic_mirrorlist /etc/pacman.d/chaotic-mirrorlist
   fi
  fi
) &
CMD_PID=$! # Capture background process PID

# Show loading animation while command is running
while kill -0 $CMD_PID 2>/dev/null; do
  for i in "" "." ".." "..."; do
    printf "\r\033[2KFinding the fastest mirrors using rate-mirrors%s" "$i"
    sleep 0.5
  done
done

echo -e "\r\033[2KMirrors updated successfully!      "
